name: Build & Deploy cxqabotcontainerapp   # uses the “2” secrets

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  ACR_LOGIN_SERVER: cxqacontaineracr.azurecr.io
  IMAGE_REPO: cxqabotcontainerapp
  RESOURCE_GROUP: cxqa_resource_group
  CONTAINER_APP: cxqabotcontainerapp
  IMAGE_TAG: ${{ github.sha }}
  IMAGE_FULL: ${{ env.ACR_LOGIN_SERVER }}/${{ env.IMAGE_REPO }}:${{ env.IMAGE_TAG }}

permissions:
  contents: read
  id-token: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      # 1 ▸ Pull your code
      - uses: actions/checkout@v3

      # 2 ▸ Azure login with the NEW secret
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS2 }}

      # 3 ▸ Build & push to ACR
      - name: Build & push image
        run: |
          az acr build \
            --registry ${{ env.ACR_LOGIN_SERVER }} \
            --image ${{ env.IMAGE_REPO }}:${{ env.IMAGE_TAG }} \
            .

      # 4 ▸ Deploy that image to the new Container App
      - name: Deploy to Container Apps
        uses: azure/container-apps-deploy@v1
        with:
          resourceGroup: ${{ env.RESOURCE_GROUP }}
          containerAppName: ${{ env.CONTAINER_APP }}
          imageToDeploy: ${{ env.IMAGE_FULL }}
          registryUrl: ${{ env.ACR_LOGIN_SERVER }}
          registryUsername: ${{ secrets.ACR_USERNAME2 }}





################
# Older container
################
# name: Build and Deploy to Azure Container Apps

# on:
#   push:
#     branches:
#       - main   # If your default branch is different, update this. 

# jobs:
#   build-and-deploy:
#     runs-on: ubuntu-latest

#     steps:
#       # 1) Check out repository
#       - name: Check out repository
#         uses: actions/checkout@v3

#       # 2) Log in to Azure
#       - name: Log in to Azure
#         uses: azure/login@v1
#         with:
#           creds: ${{ secrets.AZURE_CREDENTIALS }}

#       # 3) Build & push Docker image to ACR
#       - name: Build and push Docker image
#         run: |
#           az acr build \
#             --registry cxqacontaineracr \
#             --image cxqacontainerapp:${{ github.sha }} \
#             .

#       # 4) Configure Container App to use ACR registry
#       - name: Configure Container App registry
#         run: |
#           az containerapp registry set \
#             --resource-group cxqa_resource_group \
#             --name cxqacontainerapp \
#             --server cxqacontaineracr.azurecr.io \
#             --username ${{ secrets.ACR_USERNAME }} \
#             --password ${{ secrets.ACR_PASSWORD }}

#       # 5) Deploy the new image to Azure Container Apps..
#       - name: Deploy to Azure Container Apps
#         run: |
#           az containerapp update \
#             --resource-group cxqa_resource_group \
#             --name cxqacontainerapp \
#             --image cxqacontaineracr.azurecr.io/cxqacontainerapp:${{ github.sha }}
