name: Build and Deploy to Azure Container Apps

on:
  push:
    branches:
      - main  # Change this if your default branch is different

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: List Azure Subscriptions (for debugging)
        run: |
          az account list --output table

      - name: Build and push Docker image
        run: |
          # Replace 'cxqacontaineracr' with your actual Azure Container Registry name
          # Replace 'cxqacontainerapp' with your desired image name
          az acr build --registry cxqacontaineracr --image cxqacontainerapp:${{ github.sha }} .

      - name: Deploy to Azure Container Apps
        run: |
          # Replace 'cxqacontainerapp' with your Azure Container App name
          # Replace 'cxqa_resource_group' with your Azure Resource Group name
          # Replace 'cxqacontaineracr' with your Azure Container Registry name if needed
          az containerapp update \
            --name cxqacontainerapp \
            --resource-group cxqa_resource_group \
            --image cxqacontaineracr.azurecr.io/cxqacontainerapp:${{ github.sha }}
