name: Build and Deploy to Azure Container Apps
on:
  push: { branches: [ main ] }
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write    # <-- lets azure/login obtain an OIDC token
      contents: read

    steps:
    - name: Check out repo
      uses: actions/checkout@v4

    # 1️⃣  Sign in to Azure with the service-principal JSON in AZURE_CREDENTIALS
    - name: Azure login (OIDC)
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    # 2️⃣  Log in to ACR using that Azure context
    - name: ACR login (az acr login)
      uses: azure/cli@v2
      with:
        inlineScript: |
          az acr login --name cxqacontaineracr

    # 3️⃣  Set up Buildx
    - name: Set up Buildx
      uses: docker/setup-buildx-action@v3

    # 4️⃣  Build & push single-arch image (no 0-byte tags)
    - name: Build & push image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        platforms: linux/amd64
        tags: cxqacontaineracr.azurecr.io/cxqacontainerapp:${{ github.sha }}

    # 5️⃣  Deploy that image to Container Apps
    - name: Deploy to Container Apps
      uses: azure/cli@v2
      with:
        inlineScript: |
          az containerapp update \
            --resource-group cxqa_resource_group \
            --name cxqacontainerapp \
            --image cxqacontaineracr.azurecr.io/cxqacontainerapp:${{ github.sha }}
